let express = require('express');
let router = express.Router();

let users = require('../src/core/user/routes/users.route');
let roles = require('../src/core/role/routes/role.route');
let action = require('../src/core/action/routes/action.route');
let modules = require('../src/core/module/routes/module.route');
let params = require('../src/core/param/routes/param.route');
let permission = require('../src/core/permission/routes/permission.route');
let menuModule = require('../src/core/menu-module/routes/menu-module.route');
let contact = require('../src/core/contact/routes/contact.route');
let file = require('../src/core/file/routes/file.route');

let apresentacaoSite = require('../src/modules/apresentacao-site/routes/apresentacao-site.route');
let apresentacaoPlanos = require('../src/modules/apresentacao-planos/routes/apresentacao-planos.route');
let sobre = require('../src/modules/sobre/routes/sobre.route');
let banner = require('../src/modules/banner/routes/banner.route');
let depoimento = require('../src/modules/depoimento/routes/depoimento.route');
let produtoServico = require('../src/modules/produto-servico/routes/produto-servico.route');
let parceiro = require('../src/modules/parceiro/routes/parceiro.route');
let operadora = require('../src/modules/operadora/routes/operadora.route');
let menu = require('../src/modules/menu/routes/menu.route');
let itemAreaCliente = require('../src/modules/item-area-cliente/routes/item-area-cliente.route');
let assuntoContato = require('../src/modules/assunto-contato/routes/assunto-contato.route');
let pagina = require('../src/modules/pagina/routes/pagina.route');
let surgimentoValem = require('../src/modules/pagina/routes/surgimento-valem.route');
let oQueE = require('../src/modules/pagina/routes/o-que-e.route');
let planosPorAdesao = require('../src/modules/pagina/routes/planos-por-adesao.route');
let quantidades = require('../src/modules/pagina/routes/quantidades.route');
let paginaDepoimentos = require('../src/modules/pagina/routes/depoimentos.route');
let paginaOperadoras = require('../src/modules/pagina/routes/operadoras.route');
let paginaEntidades = require('../src/modules/pagina/routes/entidades.route');
let areaCliente = require('../src/modules/pagina/routes/area-cliente.route');
let demonstrativoIR = require('../src/modules/pagina/routes/demonstrativo-ir.route');
let formularios = require('../src/modules/formularios/routes/formularios.route');
let siteHome = require('../src/modules/site-home/routes/site-home.route');

router.use('/user', users);
router.use('/role', roles);
router.use('/action', action);
router.use('/module', modules);
router.use('/param', params);
router.use('/permission', permission);
router.use('/menu-module', menuModule);
router.use('/contact', contact);
router.use('/file', file);
router.use('/apresentacao-site', apresentacaoSite);
router.use('/apresentacao-planos', apresentacaoPlanos);
router.use('/sobre', sobre);
router.use('/banner', banner);
router.use('/depoimentos', depoimento);
router.use('/produto-servico', produtoServico);
router.use('/parceiros', parceiro);
router.use('/operadoras', operadora);
router.use('/menu', menu);
router.use('/item-area-cliente', itemAreaCliente);
router.use('/assunto-contato', assuntoContato);
router.use('/pagina', pagina);
router.use('/pagina/surgimento-valem', surgimentoValem);
router.use('/pagina/o-que-e', oQueE);
router.use('/pagina/planos-por-adesao', planosPorAdesao);
router.use('/pagina/quantidades', quantidades);
router.use('/pagina/depoimentos', paginaDepoimentos);
router.use('/pagina/operadoras', paginaOperadoras);
router.use('/pagina/entidades', paginaEntidades);
router.use('/pagina/area-cliente', areaCliente);
router.use('/pagina/demonstrativo-ir', demonstrativoIR);
router.use('/formularios', formularios);
router.use('/conteudo-home', siteHome);

module.exports = router;